services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - .netrc:/root/.netrc # using your own, for wandb login
      - ~/work/Dataset:/app/data
    ports:
      - 8894:8888
    shm_size: '32gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - vision-model-network


# avoid conflict with other networks
networks:
  vision-model-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
